name = "StudentLaw"
uuid = "4310327c-d828-4f17-9003-2840a54937dd"
authors = ["Axel Gomez <92367498+axgmz@users.noreply.github.com>"]
version = "1.0.0"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
